import React from 'react';

export const metadata = {
  title: "Start Next.js | About",
  description: "Generated by create next app",
};

const page = () => {
    return (
        <div>
            <h2 className='text-center font-bold text-green-500'>About Page</h2>
        </div>
    );
};

export default page;